CREATE DATABASE licoresDB;

USE licoresDB;

CREATE TABLE Users
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(20) NULL,
    LastName VARCHAR(20) NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20) NULL,
    RegDate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Products
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(30) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Stock INT NOT NULL,
    RegDate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE UsersProducts
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(Id) ON DELETE CASCADE,
    RegDate DATETIME NOT NULL DEFAULT GETDATE()

)